name: Build Pulse Messenger
on: [push]

jobs:
  windows-dist:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build EXE
        run: |
          npm install -g nativefier png-to-ico
          npx png-to-ico icon.png > icon.ico
          nativefier --name "Pulse Messenger" --platform "windows" --icon "icon.ico" "https://auragram-telegram-web.hf.space" build/
          iscc installer.iss
      - uses: actions/upload-artifact@v4
        with:
          name: Pulse-Windows-Setup
          path: dist/PulseMessengerSetup.exe

  android-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Pulse-Android-APK
          path: app/build/outputs/apk/debug/app-debug.apk
